# frozen_string_literal: true

require "lutaml/model"

module LocMods
  class Error < StandardError; end

  autoload :Abstract, "loc_mods/abstract.rb"
  autoload :AccessCondition, "loc_mods/access_condition.rb"
  autoload :AlternativeName, "loc_mods/alternative_name.rb"
  autoload :Area, "loc_mods/area.rb"
  autoload :CartographicExtension, "loc_mods/cartographic_extension.rb"
  autoload :Cartographics, "loc_mods/cartographics.rb"
  autoload :CitySection, "loc_mods/city_section.rb"
  autoload :Classification, "loc_mods/classification.rb"
  autoload :Cli, "loc_mods/cli.rb"
  autoload :Collection, "loc_mods/collection.rb"
  autoload :CopyInformation, "loc_mods/copy_information.rb"
  autoload :Date, "loc_mods/date.rb"
  autoload :DateOther, "loc_mods/date_other.rb"
  autoload :Detail, "loc_mods/detail.rb"
  autoload :Edition, "loc_mods/edition.rb"
  autoload :EnumerationAndChronology, "loc_mods/enumeration_and_chronology.rb"
  autoload :Extent, "loc_mods/extent.rb"
  autoload :ExtentDefinition, "loc_mods/extent_definition.rb"
  autoload :Form, "loc_mods/form.rb"
  autoload :Genre, "loc_mods/genre.rb"
  autoload :GeographicCode, "loc_mods/geographic_code.rb"
  autoload :HierarchicalGeographic, "loc_mods/hierarchical_geographic.rb"
  autoload :HierarchicalPart, "loc_mods/hierarchical_part.rb"
  autoload :HoldingSimple, "loc_mods/holding_simple.rb"
  autoload :Identifier, "loc_mods/identifier.rb"
  autoload :ItemIdentifier, "loc_mods/item_identifier.rb"
  autoload :Language, "loc_mods/language.rb"
  autoload :LanguageTerm, "loc_mods/language_term.rb"
  autoload :Location, "loc_mods/location.rb"
  autoload :Name, "loc_mods/name.rb"
  autoload :Namespace, "loc_mods/namespace.rb"
  autoload :NamePart, "loc_mods/name_part.rb"
  autoload :NonSort, "loc_mods/non_sort.rb"
  autoload :Note, "loc_mods/note.rb"
  autoload :Occupation, "loc_mods/occupation.rb"
  autoload :OriginInfo, "loc_mods/origin_info.rb"
  autoload :Part, "loc_mods/part.rb"
  autoload :PhysicalDescription, "loc_mods/physical_description.rb"
  autoload :PhysicalDescriptionNote, "loc_mods/physical_description_note.rb"
  autoload :PhysicalLocation, "loc_mods/physical_location.rb"
  autoload :Place, "loc_mods/place.rb"
  autoload :PlaceTerm, "loc_mods/place_term.rb"
  autoload :Publisher, "loc_mods/publisher.rb"
  autoload :Record, "loc_mods/record.rb"
  autoload :RecordContentSource, "loc_mods/record_content_source.rb"
  autoload :RecordIdentifier, "loc_mods/record_identifier.rb"
  autoload :RecordInfo, "loc_mods/record_info.rb"
  autoload :RecordInfoNote, "loc_mods/record_info_note.rb"
  autoload :Region, "loc_mods/region.rb"
  autoload :RelatedItem, "loc_mods/related_item.rb"
  autoload :Role, "loc_mods/role.rb"
  autoload :RoleTerm, "loc_mods/role_term.rb"
  autoload :ScriptTerm, "loc_mods/script_term.rb"
  autoload :StringPlusLanguage, "loc_mods/string_plus_language.rb"
  autoload :StringPlusLanguagePlusAuthority,
           "loc_mods/string_plus_language_plus_authority.rb"
  autoload :StringPlusLanguagePlusSupplied,
           "loc_mods/string_plus_language_plus_supplied.rb"
  autoload :Subject, "loc_mods/subject.rb"
  autoload :SubjectName, "loc_mods/subject_name.rb"
  autoload :SubjectTitleInfo, "loc_mods/subject_title_info.rb"
  autoload :TableOfContents, "loc_mods/table_of_contents.rb"
  autoload :TargetAudience, "loc_mods/target_audience.rb"
  autoload :Temporal, "loc_mods/temporal.rb"
  autoload :Text, "loc_mods/text.rb"
  autoload :TitleInfo, "loc_mods/title_info.rb"
  autoload :TypeOfResource, "loc_mods/type_of_resource.rb"
  autoload :Url, "loc_mods/url.rb"
  autoload :XlinkNamespace, "loc_mods/xlink_namespace.rb"
  autoload :XlinkHref, "loc_mods/xlink_href.rb"
end
